### ISSUE TITLE
Attribute error when uploading quiz to Canvas

### ISSUE THREAD

**Issue by bkchang-97** [eoas-ubc/md2canvas#7]
Error I am seeing comes from bottom line. 

Uploading quiz to Canvas with following settings:
  URL = https://canvas.ubc.ca
  Token = 1122**************************************************************sYwJ
  Course ID = 51824
Traceback (most recent call last):
  File "/Users/ben/opt/miniconda3/envs/jb/bin/md2canvas", line 8, in <module>
    sys.exit(md2canvas())
  File "/Users/ben/opt/miniconda3/envs/jb/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/ben/opt/miniconda3/envs/jb/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/ben/opt/miniconda3/envs/jb/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/ben/opt/miniconda3/envs/jb/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/ben/opt/miniconda3/envs/jb/lib/python3.8/site-packages/md2canvas/command.py", line 121, in md2canvas
    j2c.upload_quiz(cv, quiz, url, token, course_id)
  File "/Users/ben/opt/miniconda3/envs/jb/lib/python3.8/site-packages/md2canvas/json2canvas.py", line 211, in upload_quiz
    new_media = update_media(url, canvas_quiz_folder, media["path"])
  File "/Users/ben/opt/miniconda3/envs/jb/lib/python3.8/site-packages/md2canvas/json2canvas.py", line 28, in update_media
    if bn in f.name:
  File "/Users/ben/opt/miniconda3/envs/jb/lib/python3.8/site-packages/canvasapi/canvas_object.py", line 17, in __getattribute__
    return super(CanvasObject, self).__getattribute__(name)
AttributeError: 'File' object has no attribute 'name'

**Comment by bkchang-97** [comment]
Running md2canvas on DemoQuiz.md.

md2canvas ~/md2canvas/examples/demo_quiz/DemoQuiz.md

**Comment by phaustin** [comment]
Closed by 46ada43
